services:
  comfyui-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    image: runpod/worker-comfyui:dev
    pull_policy: never
    environment:
      - SERVE_API_LOCALLY=true
    ports:
      - "8000:8000"
      - "8188:8188"
    volumes:
      - ./data/comfyui/output:/comfyui/output
      - ./data/runpod-volume:/runpod-volume
